# Dependencies
markdown:  kramdown
permalink: pretty
relative_permalinks: false
include: ['_pages']

# Setup
title:            'Vigy-Labyrinthe'
tagline:          'Le Labyrinthe de Vigy'
description:      'Partez sur plusieurs kilomètres, au hasard
de nouveaux chemins, à la recherche de panneaux
comportant plusieurs questionnaires sur
différents thèmes...'
url:              https://vigy-labyrinthe.fr
baseurl:          /

author:
  name:           'Adonis NAJIMI'
  url:            https://github.com/AdoPi

defaults:
  - 
    scope:
      path: "public/galery"
    values:
      images: true
